"""Execution tracing for tool calls."""
from seekflow.trace.recorder import TraceRecorder
from seekflow.trace.events import (
    TraceEvent,
    TraceRecord,
    EVENT_DEEPSEEK_REQUEST_BUILT,
    EVENT_DEEPSEEK_PROTOCOL_VALIDATED,
    EVENT_DEEPSEEK_RESPONSE_RECEIVED,
    EVENT_TOOL_POLICY_CHECKED,
    EVENT_TOOL_APPROVAL_REQUESTED,
    EVENT_TOOL_EXECUTION_STARTED,
    EVENT_TOOL_EXECUTION_FINISHED,
    EVENT_RETRY_SCHEDULED,
    EVENT_CIRCUIT_OPENED,
    EVENT_BUDGET_PREFLIGHT_CHECKED,
    EVENT_CACHE_PREFIX_COMPILED,
    ALL_CANONICAL_EVENTS,
)

__all__ = [
    "TraceRecorder",
    "TraceEvent",
    "TraceRecord",
    "EVENT_DEEPSEEK_REQUEST_BUILT",
    "EVENT_DEEPSEEK_PROTOCOL_VALIDATED",
    "EVENT_DEEPSEEK_RESPONSE_RECEIVED",
    "EVENT_TOOL_POLICY_CHECKED",
    "EVENT_TOOL_APPROVAL_REQUESTED",
    "EVENT_TOOL_EXECUTION_STARTED",
    "EVENT_TOOL_EXECUTION_FINISHED",
    "EVENT_RETRY_SCHEDULED",
    "EVENT_CIRCUIT_OPENED",
    "EVENT_BUDGET_PREFLIGHT_CHECKED",
    "EVENT_CACHE_PREFIX_COMPILED",
    "ALL_CANONICAL_EVENTS",
]
