from __future__ import annotations

from seekflow_engineering_tools.geometry_primitives.base import PrimitiveDefinition, PrimitiveParameter

GEAR_PRIMITIVES: list[PrimitiveDefinition] = [
    PrimitiveDefinition(
        name="involute_spur_gear",
        category="gear",
        description="Standard involute spur gear — deterministic BREP via CQ_Gears kernel.",
        parameters=[
            PrimitiveParameter(name="module_mm", type="float", unit="mm", required=True,
                               min_value=0.05, description="Module (m) in mm"),
            PrimitiveParameter(name="teeth", type="int", required=True,
                               min_value=6, description="Number of teeth (z)"),
            PrimitiveParameter(name="pressure_angle_deg", type="float", unit="deg",
                               required=False, default=20.0,
                               min_value=14.5, max_value=30.0,
                               description="Pressure angle in degrees"),
            PrimitiveParameter(name="face_width_mm", type="float", unit="mm", required=True,
                               min_value=0.1, description="Face width in mm"),
            PrimitiveParameter(name="bore_dia_mm", type="float", unit="mm",
                               required=False, default=0.0, min_value=0.0,
                               description="Centre bore diameter (0 = no bore)"),
            PrimitiveParameter(name="addendum_coefficient", type="float",
                               required=False, default=1.0,
                               min_value=0.5, max_value=1.5,
                               description="Addendum coefficient (ha*)"),
            PrimitiveParameter(name="clearance_coefficient", type="float",
                               required=False, default=0.25,
                               min_value=0.05, max_value=0.6,
                               description="Clearance coefficient (c*)"),
            PrimitiveParameter(name="profile_shift_coefficient", type="float",
                               required=False, default=0.0,
                               min_value=-1.0, max_value=1.0,
                               description="Profile shift coefficient (x)"),
            PrimitiveParameter(name="backlash_mm", type="float", unit="mm",
                               required=False, default=0.0, min_value=0.0,
                               description="Backlash in mm"),
            PrimitiveParameter(name="root_fillet_radius_mm", type="float", unit="mm",
                               required=False, default=0.0, min_value=0.0,
                               description="Root fillet radius in mm"),
            PrimitiveParameter(name="quality_grade", type="str",
                               required=False, default="industrial_brep",
                               description="Quality grade: industrial_brep or validated"),
        ],
        supported_kernels=["cq_gears", "cadquery_visual_fallback"],
        supported_backends=["cadquery", "solidworks2025", "nx12"],
        standards=["ISO_53_like", "DIN_867_like"],
        validation_defaults={"expected_body_count": 1, "tolerance_mm": 0.05},
    ),
]
